### ISSUE TITLE
new template

### ISSUE THREAD

**Issue by burggraeve9** [FatihKoz/JumpSeat#2]
hello i have a template can you work on it? 
If you are ok I can share it
https://preview.themeforest.net/item/dashtic-laravel-dashboard-template/full_screen_preview/28341521?_ga=2.143385397.1463758826.1620686324-2136348216.1620686301

**Comment by FatihKoz** [comment]
Sorry, I do not understand your question ... What is the relation between above link and JumpSeat Travel module ?

If you are asking me to work on a template and make it adapted/customized for your phpvms v7 installation , sorry I do not work as a freelancer for personal requests.

If your theme is already adapted/customized for phpvms v7 and you are asking for a modified widget blade, maybe I can help you with suggestions about styling.
